### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-NoeliaGlez#1]
[Infografía Realidad Aumentada (2).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-NoeliaGlez/files/14301363/Infografia.Realidad.Aumentada.2.pdf)

**Comment by ElisabetRD** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
